version: 2
jobs:
  build_and_deploy:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: apk add --no-cache --no-progress bash openssh
      - run: scripts/deploy.bash
workflows:
  version: 2
  ci:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
